### ISSUE TITLE
Configurations with multiple regions show the values of one region on all regions

### ISSUE THREAD

**Issue by chrisp250** [bacco007/sensor.opennem#8]
## Version of the custom_component
Current/latest version

## Configuration
Config inside sensor.yaml
```yaml
- platform: opennem
  name: "AEMO NSW"
  region: nsw1
  monitored_conditions:
    - exports
    - demand
    - distillate
    - fossilfuel
    - renewables
    - generation
    - hydro
    - imports
    - price
    - pumps
    - solar_rooftop
    - solar_utility
    - temperature
    - wind
- platform: opennem
  name: "AEMO VIC"
  region: vic1
  monitored_conditions:
    - exports
    - demand
    - distillate
    - fossilfuel
    - renewables
    - generation
    - hydro
    - imports
    - price
    - pumps
    - solar_rooftop
    - solar_utility
    - temperature
    - wind
```

Add your logs here.
```
Not sure how to extract the logs. Happy to do that if I can get hand.
```
## Describe the bug
When configuring multiple regions, all regions show the same information.
In this case I configured NSW and Victoria, and while NSW sensors are always correct, Victoria's seem to be toggling between the NSW and the Victoria data. See the graph attached.

I'm running the last/current version from GitHub.

<img width="399" alt="Screen Shot 2022-01-04 at 9 29 55 am" src="https://user-images.githubusercontent.com/2541959/147987649-4b87b2e5-27fc-440d-9351-e1177a47f7b3.png">

## Debug log
```text
<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->



Add your logs here.

```
